<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="opmeta"
    nsURI="www.vainolo.com/phd/opmeta" nsPrefix="opmeta">
  <eClassifiers xsi:type="ecore:EClass" name="OPMetaModelDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ElementsDiagram" lowerBound="1"
        eType="ecore:EClass ../../com.vainolo.phd.opm.model/model/opm.ecore#//OPMObjectProcessDiagram"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LinksDiagram" lowerBound="1"
        eType="ecore:EClass ../../com.vainolo.phd.opm.model/model/opm.ecore#//OPMObjectProcessDiagram"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OPMetaModelContaimentValidationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMetaModelLinkValidationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="MetaModel" eType="#//OPMetaModelDiagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Container" lowerBound="1"
        eType="#//ContainerInstanceBase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NextId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceBase" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TypeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeInstanceBase" eSuperTypes="#//InstanceBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraints" eType="ecore:EDataType ../../com.vainolo.phd.opm.model/model/opm.ecore#//Rectangle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLinks" upperBound="-1"
        eType="#//LinkInstanceBase" eOpposite="#//LinkInstanceBase/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingLinks" upperBound="-1"
        eType="#//LinkInstanceBase" eOpposite="#//LinkInstanceBase/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerInstanceBase" eSuperTypes="#//InstanceBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//NodeInstanceBase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//LinkInstanceBase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkInstanceBase" eSuperTypes="#//InstanceBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//NodeInstanceBase"
        eOpposite="#//NodeInstanceBase/outgoingLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//NodeInstanceBase"
        eOpposite="#//NodeInstanceBase/incomingLinks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThingInstanceBase" eSuperTypes="#//NodeInstanceBase #//ContainerInstanceBase"/>
</ecore:EPackage>
