<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="opmeta"
    nsURI="http://opmeta/1.0" nsPrefix="opmeta">
  <eClassifiers xsi:type="ecore:EClass" name="OPMetaModelDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Types" upperBound="-1"
        eType="#//OPMetaModelTypeDefinitions" unsettable="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Links" upperBound="-1"
        eType="#//OPMetaModelLinkTypeDefintion" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LinkValidations" upperBound="-1"
        eType="#//OPMetaModelLinkValidationRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ContainmentValidations"
        upperBound="-1" eType="#//OPMetaModelContaimentValidationRule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OPMetaModelTypeDefinitions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parents" upperBound="-1"
        eType="#//OPMetaModelTypeDefinitions" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VisualDara" lowerBound="1"
        eType="#//OPMetaModelVisualData" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Properties" upperBound="-1"
        eType="#//OPMetaModelProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OPMetaTypeBehaviourKind">
    <eLiterals name="NodeBehaviour" value="1"/>
    <eLiterals name="ContainerBehaiour" value="2"/>
    <eLiterals name="ThingBehaviour" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OPMetaModelVisualData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraints" lowerBound="1"
        eType="ecore:EDataType ../../com.vainolo.phd.opm.model/model/opm.ecore#//Rectangle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OPMetaModelProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//OPMetaModelPropertyKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OPMetaModelPropertyKind">
    <eLiterals name="STRING"/>
    <eLiterals name="LONG" value="1"/>
    <eLiterals name="DOUBLE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OPMetaModelLinkTypeDefintion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="VisualData" eType="#//OPMetaModelVisualData"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetDecoration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceDecoration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="centerDecoration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OPMetaModelLinkValidationRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LinkType" lowerBound="1"
        eType="#//OPMetaModelLinkTypeDefintion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceType" lowerBound="1"
        eType="#//OPMetaModelTypeDefinitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetType" eType="#//OPMetaModelTypeDefinitions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsValid" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OPMetaModelContaimentValidationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsValid" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ContainerType" lowerBound="1"
        eType="#//OPMetaModelTypeDefinitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeType" lowerBound="1"
        eType="#//OPMetaModelTypeDefinitions"/>
  </eClassifiers>
</ecore:EPackage>
